references_dir: 'references_dir'

# See the reference config files in the top level of the repo,
# include/reference_configs, for inspiration for more species.
include_references:
  - 'reference_configs/Drosophila_melanogaster.yaml'