fastq_R1: '../output/{sample}/{sample}_R1.fastq.gz'
fastq_R2: '../output/{sample}/{sample}_R2.fastq.gz'
cutadapt_R1: '../output/{sample}/{sample}_R1.cutadapt.fastq.gz'
cutadapt_R2: '../output/{sample}/{sample}_R2.cutadapt.fastq.gz'
bam: '../output/{sample}/{sample}.cutadapt.bam'
merged_bam: '../output/heads.bam'
bamList: '../output/bamlist.txt'
# TODO fix stringtie sample names to add params
stringtie: '../output/stringtie/head.gtf'
stringtie_single: '../output/stringtie/single_setting_{setting}.gtf'
gffcompare_single:
  stats: '../output/stringtie/gffcmp_{setting}.stats'
  loci: '../output/stringtie/gffcmp_{setting}.loci'
  gtf: '../output/stringtie/gffcmp_{setting}.annotated.gtf'
  tracking: '../output/stringtie/gffcmp_{setting}.tracking'
