fastq: 'output/{sample}/{sample}_R{n}.fastq.gz'
cutadapt: 'output/{sample}/{sample}_R{n}.cutadapt.fastq.gz'
bam: 'output/{sample}/{sample}.cutadapt.bam'
bam_merge: 'output/heads.bam'
# TODO fix stringtie sample names to add params
stringtie: 'output/stringtie/{sample}/'
